### ISSUE TITLE
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host mirrors.aliyun.com:443 ssl:default [Network is unreachable]

### ISSUE THREAD

**Issue by baldfang** [pypa/bandersnatch#1070]
1. bandersnatch 5.1.1,python Python 3.8.8 for environment.

[root@pypi-repo-server pypi]# bandersnatch --debug mirror
2021-12-18 04:57:07,452 DEBUG: Checking config for storage backend... (configuration.py:120)
2021-12-18 04:57:07,452 DEBUG: Found storage backend in config! (configuration.py:122)
2021-12-18 04:57:07,452 INFO: Selected storage backend: filesystem (configuration.py:128)
2021-12-18 04:57:07,452 DEBUG: Checking config for compare method... (configuration.py:160)
2021-12-18 04:57:07,452 DEBUG: Found compare method in config! (configuration.py:162)
2021-12-18 04:57:07,453 INFO: Selected compare method: hash (configuration.py:174)
2021-12-18 04:57:07,453 DEBUG: Checking config for alternative download mirror... (configuration.py:177)
2021-12-18 04:57:07,453 INFO: Selected alternative download mirror https://mirrors.aliyun.com/pypi/simple/ (configuration.py:179)
2021-12-18 04:57:07,453 DEBUG: Checking config for only download from alternative downloadmirror... (configuration.py:186)
2021-12-18 04:57:07,453 DEBUG: Setting to fallback to original if download mirror fails (configuration.py:196)
2021-12-18 04:57:07,542 DEBUG: Initializing Master's aiohttp ClientSession (master.py:79)
2021-12-18 04:57:07,633 DEBUG: Retrieving FileLock instance @ /srv/pypi/.lock (filesystem.py:36)
2021-12-18 04:57:07,633 DEBUG: Acquiring FLock with timeout: 1 (mirror.py:544)
2021-12-18 04:57:07,634 DEBUG: File not changed...deleting temporary file: /srv/pypi/generation.5j6cnizh (filesystem.py:120)
2021-12-18 04:57:07,634 INFO: Status file /srv/pypi/status missing. Starting over. (mirror.py:601)
2021-12-18 04:57:07,634 INFO: Syncing with https://mirrors.aliyun.com/pypi/simple/. (mirror.py:56)
2021-12-18 04:57:07,634 INFO: Current mirror serial: 0 (mirror.py:267)
2021-12-18 04:57:07,634 INFO: Syncing all packages. (mirror.py:282)
2021-12-18 04:57:08,721 DEBUG: Closing Master's aiohttp ClientSession and waiting 0.1 seconds (master.py:99)
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/python3/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/python3/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/python3/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/python3/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/python3/lib/python3.8/asyncio/selector_events.py", line 501, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3/bin/bandersnatch", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.8/site-packages/bandersnatch/main.py", line 219, in main
    return asyncio.run(async_main(args, config))
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/python3/lib/python3.8/site-packages/bandersnatch/main.py", line 184, in async_main
    return await bandersnatch.mirror.mirror(config)
  File "/usr/local/python3/lib/python3.8/site-packages/bandersnatch/mirror.py", line 1041, in mirror
    changed_packages = await mirror.synchronize(specific_packages)
  File "/usr/local/python3/lib/python3.8/site-packages/bandersnatch/mirror.py", line 64, in synchronize
    await self.determine_packages_to_sync()
  File "/usr/local/python3/lib/python3.8/site-packages/bandersnatch/mirror.py", line 286, in determine_packages_to_sync
    all_packages = await self.master.all_packages()
  File "/usr/local/python3/lib/python3.8/site-packages/bandersnatch/master.py", line 221, in all_packages
    all_packages_with_serial = await self.rpc("list_packages_with_serial")
  File "/usr/local/python3/lib/python3.8/site-packages/bandersnatch/master.py", line 216, in rpc
    return await method()
  File "/usr/local/python3/lib/python3.8/site-packages/aiohttp_xmlrpc/client.py", line 110, in __remote_call
    async with self.client.post(
  File "/usr/local/python3/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/python3/lib/python3.8/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/python3/lib/python3.8/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/python3/lib/python3.8/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/python3/lib/python3.8/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/python3/lib/python3.8/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/python3/lib/python3.8/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host mirrors.aliyun.com:443 ssl:default [Network is unreachable]

2. bandersnatch.conf
[root@pypi-repo-server pypi]# cat /etc/bandersnatch.conf 
[mirror]
; The directory where the mirror data will be stored.
directory = /srv/pypi
; Save JSON metadata into the web tree:
; URL/pypi/PKG_NAME/json (Symlink) -> URL/json/PKG_NAME
json = false

; Save package release files
release-files = true

; Cleanup legacy non PEP 503 normalized named simple directories
cleanup = false

; The PyPI server which will be mirrored.
; master = https://test.python.org
; scheme for PyPI server MUST be https
; master = https://pypi.org
master = https://mirrors.aliyun.com/pypi/simple/

; The network socket timeout to use for all connections. This is set to a
; somewhat aggressively low value: rather fail quickly temporarily and re-run
; the client soon instead of having a process hang infinitely and have TCP not
; catching up for ages.
timeout = 10

; The global-timeout sets aiohttp total timeout for it's coroutines
; This is set incredibly high by default as aiohttp coroutines need to be
; equipped to handle mirroring large PyPI packages on slow connections.
global-timeout = 1800

**Comment by cooperlees** [comment]
Hi,

I’m guessing you worked out network network issue? This couldn’t have ever been bandersnatch’s fault, and very low chance it was aiohttp.

What was it?

Cheers

**Comment by baldfang** [comment]
Hi,

I'm modify /usr/local/python3/lib/python3.8/site-packages/aiohttp/connector.py verify_ssl: bool = False,use_dns_cache: bool = False, I think it is verify_ssl: bool = False,use_dns_cache: bool = False. 

Now bandersnatch is running properly.

Cheers

**Comment by cooperlees** [comment]
Ok, I would have went about this the reverse way and fixed the SSL certificate on the mirror you're using.

We could, but I'm not keen on it, expose these settings to bandersnatch config if desired in a [aiohttp] section maybe and see it on all the aiohttp usages of bandersnatch.
