### ISSUE TITLE
TimeoutError downloading release files for bandersnatch 5.1.1 + py3.8 mirror 

### ISSUE THREAD

**Issue by galesauryan** [pypa/bandersnatch#1136]
hi,
the bandersnatch mirror can't work smoothly for almost 2 months. The error shows time out. How to fix it?
===========================
[root@Server-sc0r86 Python-3.8.0]# bandersnatch/bin/bandersnatch --version
bandersnatch 5.1.1
[root@Server-sc0r86 Python-3.8.0]# python3 --version
Python 3.8.0
[root@Server-sc0r86 pypi]# ll
-rw-r--r-- 1 10032 10001   349919 Jun 15 14:12 pypi202206141655169932.log
-rw------- 1 10032 10001        8 Apr 21 16:30 status
-rw------- 1 10032 10001    24860 May 30 16:51 todo
drwxr-xr-x 5 10032 10001        0 Apr 21 16:30 web
------------------
part of pypi202206141655169932.log
2022-06-15 13:35:34,391 INFO: Downloading: https://files.pythonhosted.org/packages/22/e8/a695f30e0199f58903e3409086a83f0e57f498cc5e6440975995725bae53/tf_nightly_cpu-2.10.0.dev20220429-cp310-cp310-macosx_10_14_x86_64.whl (mirror.py:933)
2022-06-15 13:35:45,104 ERROR: Continuing to next file after error downloading: https://files.pythonhosted.org/packages/22/e8/a695f30e0199f58903e3409086a83f0e57f498cc5e6440975995725bae53/tf_nightly_cpu-2.10.0.dev20220429-cp310-cp310-macosx_10_14_x86_64.whl (mirror.py:722)
Traceback (most recent call last):
  File "/software/Python-3.8.0/bandersnatch/lib/python3.8/site-packages/bandersnatch/mirror.py", line 698, in sync_release_files
    downloaded_file = await self.download_file(
  File "/software/Python-3.8.0/bandersnatch/lib/python3.8/site-packages/bandersnatch/mirror.py", line 946, in download_file
    response = await r_generator.asend(None)
  File "/software/Python-3.8.0/bandersnatch/lib/python3.8/site-packages/bandersnatch/master.py", line 152, in get
    async with self.session.get(path, **kw) as r:
  File "/software/Python-3.8.0/bandersnatch/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/software/Python-3.8.0/bandersnatch/lib/python3.8/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/software/Python-3.8.0/bandersnatch/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/software/Python-3.8.0/bandersnatch/lib/python3.8/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerTimeoutError: Timeout on reading data from socket
2022-06-15 13:35:45,124 INFO: Downloading: https://files.pythonhosted.org/packages/9a/6c/e9cdb6546f146f1e0f245096339963a28f29eb5f9ec42d3cf5d2539a067d/tf_nightly_cpu-2.10.0.dev20220429-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (mirror.py:933)
2022-06-15 13:42:12,369 ERROR: Continuing to next file after error downloading: https://files.pythonhosted.org/packages/a9/4e/fc1777673b327e812717b0aa96b942e264eda21923731b5053692cd05df1/tf_nightly-2.10.0.dev20220429-cp37-cp37m-macosx_10_14_x86_64.whl (mirror.py:722)
Traceback (most recent call last):
  File "/software/Python-3.8.0/bandersnatch/lib/python3.8/site-packages/bandersnatch/mirror.py", line 698, in sync_release_files
    downloaded_file = await self.download_file(
  File "/software/Python-3.8.0/bandersnatch/lib/python3.8/site-packages/bandersnatch/mirror.py", line 952, in download_file
    chunk = await response.content.read(chunk_size)
  File "/software/Python-3.8.0/bandersnatch/lib/python3.8/site-packages/aiohttp/streams.py", line 385, in read
    await self._wait("read")
  File "/software/Python-3.8.0/bandersnatch/lib/python3.8/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
  File "/software/Python-3.8.0/bandersnatch/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
2022-06-15 13:42:12,389 INFO: Downloading: https://files.pythonhosted.org/packages/0e/a5/5fd01bd36b3052b2e17afac7962ac6c9463b4b4f65efa142429cd5cc3c1b/tf_nightly-2.10.0.dev20220429-cp38-cp38-macosx_10_14_x86_64.whl (mirror.py:933)
--------------------------
[root@Server-sc0r86 Python-3.8.0]# ping files.pythonhosted.org
PING dualstack.r.ssl.global.fastly.net (151.101.109.63) 56(84) bytes of data.
64 bytes from 151.101.109.63 (151.101.109.63): icmp_seq=1 ttl=49 time=92.7 ms
64 bytes from 151.101.109.63 (151.101.109.63): icmp_seq=2 ttl=49 time=92.5 ms
64 bytes from 151.101.109.63 (151.101.109.63): icmp_seq=4 ttl=49 time=92.3 ms
64 bytes from 151.101.109.63 (151.101.109.63): icmp_seq=5 ttl=49 time=91.8 ms
64 bytes from 151.101.109.63 (151.101.109.63): icmp_seq=6 ttl=49 time=91.8 ms
64 bytes from 151.101.109.63 (151.101.109.63): icmp_seq=8 ttl=49 time=91.8 ms

The network seems ok, but the mirror doesn't work. :(

**Comment by cooperlees** [comment]
Howdy,

Generally if people see timeouts I recommend turning down the `workers` to cause less parallelism. What do you have it set at in your config?
- https://github.com/pypa/bandersnatch/blob/main/src/bandersnatch/default.conf#L35

This could be bother your Network connection and your underlying storage for the artifacts causing this. Ping shows reach-ability and potential loss, but not link saturation etc. - What kind of connection is bandersnatch behind? Another test that could be good to rule out your connect is using wget to the same filesystem to down X (where X == your worker setting) files at the same time and see if it occurs network timeouts too.

Let me know how these tests go.

**Comment by galesauryan** [comment]
Hi,

 

       Thank you for your help. J

       The file of bandersnatch.conf is almost default, I just modified the store directory of the mirror data, and  workers = 3.

***@***.***

       And you are absolutely correct. It seems the trouble with our bad network transmission rate. I did the test as your suggestion to wget one file, it can connect, but the speed is only 25KB/s, the file will take more than 3 hours.

***@***.***

       But the mirror was running smoothly before April 21th, I asked our network managers about this issue, they said they hadn’t change the network configuration recently. I have no idea in this situation. L

 

zhangyan

2022-06-17

 

发件人: ***@***.*** ***@***.*** 代表 Cooper Lees
发送时间: 2022年6月16日 0:03
收件人: pypa/bandersnatch
抄送: galesauryan; Author
主题: Re: [pypa/bandersnatch] TimeoutError for bandersnatch mirror (Issue #1136)

 

Howdy,

Generally if people see timeouts I recommend turning down the workers to cause less parallelism. What do you have it set at in your config?

*	https://github.com/pypa/bandersnatch/blob/main/src/bandersnatch/default.conf#L35

This could be bother your Network connection and your underlying storage for the artifacts causing this. Ping shows reach-ability and potential loss, but not link saturation etc. - What kind of connection is bandersnatch behind? Another test that could be good to rule out your connect is using wget to the same filesystem to down X (where X == your worker setting) files at the same time and see if it occurs network timeouts too.

Let me know how these tests go.

**Comment by cooperlees** [comment]
I think this is a connectivity issue here. So I'm going to close. Let us know if you prove otherwise.

**Comment by galesauryan** [comment]
Ok, thank you so much~

 

发件人: ***@***.*** ***@***.*** 代表 Cooper Lees
发送时间: 2022年6月21日 1:12
收件人: pypa/bandersnatch
抄送: galesauryan; Author
主题: Re: [pypa/bandersnatch] TimeoutError downloading release files for bandersnatch 5.1.1 + py3.8 mirror (Issue #1136)

 

I think this is a connectivity issue here. So I'm going to close. Let us know if you prove otherwise.
