### ISSUE TITLE
"File name too long" error on centos7.2

### ISSUE THREAD

**Issue by 89ao** [pypa/bandersnatch#1200]
when I was running "bandersnatch sync uselesscapitalquiz" I got this error "OSError: [Errno 36] File name too long".
After some research ,It seems that the full path+filename have pass over the max-filename of the linux system which is 255bits.

This situation happens in bandersnatch 4.4/5.3 and 6.0,please help me solve this problems,thanks a lot .

```
[root@VM_21_104_centos /data/home/bandersnatch]# **bandersnatch sync uselesscapitalquiz**
2022-09-04 11:05:36,838 INFO: Selected storage backend: filesystem
2022-09-04 11:05:37,053 ERROR: Unable to load entry point swift_plugin = bandersnatch_storage_plugins.swift:SwiftStorage: No module named 'keystoneauth1'
2022-09-04 11:05:37,227 INFO: Syncing with https://pypi.python.org.
2022-09-04 11:05:37,228 INFO: No metadata filters are enabled. Skipping metadata filtering
2022-09-04 11:05:37,228 INFO: No release filters are enabled. Skipping release filtering
2022-09-04 11:05:37,228 INFO: No release file filters are enabled. Skipping release file filtering
2022-09-04 11:05:37,229 INFO: Fetching metadata for package: uselesscapitalquiz (serial 0)
2022-09-04 11:05:38,667 INFO: Downloading: https://files.pythonhosted.org/packages/74/b6/d3fe5583d610652a0ce8613b05922b62a1fab89a4804eb8977f8ff2b2814/uselesscapitalquiz-3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651328230664709384460955058223172535940812848111745028410270193852110555964462294895493038196442881097566593-py3-none-any.whl
2022-09-04 11:05:40,229 ERROR: Continuing to next file after error downloading: https://files.pythonhosted.org/packages/74/b6/d3fe5583d610652a0ce8613b05922b62a1fab89a4804eb8977f8ff2b2814/uselesscapitalquiz-3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651328230664709384460955058223172535940812848111745028410270193852110555964462294895493038196442881097566593-py3-none-any.whl
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/bandersnatch/mirror.py", line 644, in sync_release_files
    release_file["url"], release_file["digests"]["sha256"]
  File "/usr/local/lib/python3.6/site-packages/bandersnatch/mirror.py", line 806, in download_file
    with self.storage_backend.rewrite(path, "wb") as f:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/bandersnatch_storage_plugins/filesystem.py", line 82, in rewrite
    mode=mode, prefix=f".{filename}.", delete=False, dir=base_dir, **kw
  File "/usr/lib64/python3.6/tempfile.py", line 551, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib64/python3.6/tempfile.py", line 262, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
**OSError: [Errno 36] File name too long: '/yum/pip/web/packages/74/b6/d3fe5583d610652a0ce8613b05922b62a1fab89a4804eb8977f8ff2b2814/.uselesscapitalquiz-3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651328230664709384460955058223172535940812848111745028410270193852110555964462294895493038196442881097566593-py3-none-any.whl.whcr0jsj'**
2022-09-04 11:05:40,289 ERROR: Error syncing package: uselesscapitalquiz@0
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/bandersnatch/mirror.py", line 132, in package_syncer
    await self.process_package(package)
  File "/usr/local/lib/python3.6/site-packages/bandersnatch/mirror.py", line 319, in process_package
    await self.sync_release_files(package)
  File "/usr/local/lib/python3.6/site-packages/bandersnatch/mirror.py", line 656, in sync_release_files
    raise deferred_exception  # raise the exception after trying all files
  File "/usr/local/lib/python3.6/site-packages/bandersnatch/mirror.py", line 644, in sync_release_files
    release_file["url"], release_file["digests"]["sha256"]
  File "/usr/local/lib/python3.6/site-packages/bandersnatch/mirror.py", line 806, in download_file
    with self.storage_backend.rewrite(path, "wb") as f:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/bandersnatch_storage_plugins/filesystem.py", line 82, in rewrite
    mode=mode, prefix=f".{filename}.", delete=False, dir=base_dir, **kw
  File "/usr/lib64/python3.6/tempfile.py", line 551, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib64/python3.6/tempfile.py", line 262, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 36] File name too long: '/yum/pip/web/packages/74/b6/d3fe5583d610652a0ce8613b05922b62a1fab89a4804eb8977f8ff2b2814/.uselesscapitalquiz-3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651328230664709384460955058223172535940812848111745028410270193852110555964462294895493038196442881097566593-py3-none-any.whl.whcr0jsj'
2022-09-04 11:05:40,290 INFO: Generating global index page.
2022-09-04 11:05:49,331 INFO: Removing file: /yum/pip/web/simple/.index.html.coiw2wao
2022-09-04 11:05:49,432 INFO: 0 packages had changes
2022-09-04 11:05:49,432 INFO: Writing diff file to mirrored-files
```

**Comment by 89ao** [comment]
And here is my bandersnatch.conf:
```
[root@VM_21_xxx_centos /data/home/motorao/bandersnatch]# cat /etc/redhat-release 
CentOS Linux release 7.2 (Final)
[root@VM_21_xxx_centos /data/home/motorao/bandersnatch]# cat bandersnatch.conf 
[mirror]
directory = /opt/bandersnatch
json = false
release-files = true
;cleanup = false
master = https://pypi.python.org
timeout = 30
global-timeout = 300
workers = 10
hash-index = false
stop-on-error = false
storage-backend = filesystem
proxy = http://x.x.x.x:3128
delete-packages = true
log-config = /conf/bandersnatch-log.conf
verifiers = 3




;root_uri = https://example.comverifiers = 3
;keep_index_versions = 0
;vim: set ft=cfg:
;diff-file = /srv/pypi/mirrored-files
;diff-append-epoch = true
```

**Comment by cooperlees** [comment]
This is an OS limitation we can't really fix. You'd have to see if there is a filesystem that CentOS can run that can support this. Do you really need this pacakge? Seems the have quite crazy versioning:

Version example (from https://pypi.org/pypi/uselesscapitalquiz/json):
```
"version": "3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651328230664709384460955058223172535940812848111745028410270193852110555964462294895493038196442881097566593",
```

```
/yum/pip/web/packages/74/b6/d3fe5583d610652a0ce8613b05922b62a1fab89a4804eb8977f8ff2b2814/.uselesscapitalquiz-3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651328230664709384460955058223172535940812848111745028410270193852110555964462294895493038196442881097566593-py3-none-any.whl.whcr0jsj
```

**Comment by 89ao** [comment]
thanks a lot ,now I have understand this situation.

**Comment by 89ao** [comment]
solution:simplely add this to your bandersnatch.conf

```
[plugins]
enabled =
    blocklist_project
    blocklist_release

[blocklist]
packages =
    uselesscapitalquiz
```

**Comment by jasom** [comment]
One thing of note is that no filenames of files in uselesscapitalquiz exceed 255 characters (the longest is 253).  When downloading a file, bandersnatch appends a random string (e.g. `.whcr0jsj` in the logs posted above) which makes the filename longer.  This means that even if PEP-440 is amended to keep the wheel-file name under 255 characters, bandersnatch could still have problems.  Is it reasonable for bandersnatch to at least not *lengthen* the filename when downloading?  (Or perhaps not lengthening it above 255 characters, keeping the existing behavior for shorter filenames, and using maybe a hash when the filename is very long)?

**Comment by cooperlees** [comment]
Definitely possible, but today we use NamedTemporaryFile from tempfile stdlib module. 

https://github.com/pypa/bandersnatch/blob/main/src/bandersnatch/utils.py#LL109C12-L109C12

We could move to a non named temporary file I guess too if people feel it's desirable? https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryFile
