### ISSUE TITLE
bandersnatch.master.XmlRpcError: Unable to get full list of packages

### ISSUE THREAD

**Issue by lxyeternal** [pypa/bandersnatch#1370]
I can't mirror the pypi packages from [https://pypi.org](url)
This is my bandersnatch.cfg

[mirror]
directory = /data1/gwb/pypi  
json = true  
release-files = true  
cleanup = false  
master = https://pypi.org  
timeout = 10  
global-timeout = 1800  
workers = 5  
hash-index = false  
simple-format = ALL  
stop-on-error = false  
storage-backend = filesystem  
log-config = /etc/bandersnatch-log.conf  
verifiers = 3  
compare-method = hash  
download-mirror = https://pypi.tuna.tsinghua.edu.cn/  
download-mirror-no-fallback = False  
[plugins]  
enabled =  
    size_project_metadata  
[allowlist]  
packages =  
    flask  
[size_project_metadata]  
max_package_size = 1G

**Comment by cooperlees** [comment]
An XML RPC error can only fail due to your connection (could be a timeout for exmaple) or an issue with PyPI.org itself. Without a stack trace I have no way of telling what was your cause here. Please repopen if there is more info, but it is unlikely a bandersnatch bug.

**Comment by qomhmd** [comment]
I'm trying to run bandersnatch inside an AlmaLinux WSL under Windows 11. I can ping google.com from inside the WSL. When running `bandersnatch mirror`, I am gettibg this trace:
```
2024-12-21 20:35:57,481 INFO: Selected storage backend: filesystem (configuration.py:131)
2024-12-21 20:35:57,481 INFO: Selected compare method: hash (configuration.py:179)
2024-12-21 20:35:57,546 INFO: Initialized project plugin allowlist_project, filtering ['black'] (allowlist_name.py:33)
2024-12-21 20:35:57,547 INFO: Initialized project plugin blocklist_project, filtering [] (blocklist_name.py:27)
2024-12-21 20:35:57,548 INFO: Initialized project plugin project_requirements, filtering [] (allowlist_name.py:33)
2024-12-21 20:35:57,553 WARNING: Unable to initialise size_project_metadata plugin;must create max_package_size in configuration. (metadata_filter.py:203)
2024-12-21 20:35:57,554 INFO: Initialized release plugin allowlist_release, filtering [<Requirement('black==18.5')>] (allowlist_name.py:180)
2024-12-21 20:35:57,555 INFO: Initialized release plugin blocklist_release, filtering [] (blocklist_name.py:110)
2024-12-21 20:35:57,557 INFO: Initialized prerelease plugin with [re.compile('.+rc\\d+$'), re.compile('.+a(lpha)?\\d+$'), re.compile('.+b(eta)?\\d+$'), re.compile('.+dev\\d+$')] (prerelease_name.py:36)
2024-12-21 20:35:57,557 INFO: Initialized prerelease plugin prerelease_release, filtering all packages (prerelease_name.py:48)
2024-12-21 20:35:57,557 INFO: Initialized release plugin project_requirements_pinned, filtering [] (allowlist_name.py:180)
2024-12-21 20:35:57,559 ERROR: Plugin exclude_platform: missing platforms= setting (filename_name.py:72)
2024-12-21 20:35:57,561 INFO: Status file /srv/pypi/status missing. Starting over. (mirror.py:566)
2024-12-21 20:35:57,561 INFO: Syncing with https://pypi.org. (mirror.py:57)
2024-12-21 20:35:57,561 INFO: Current mirror serial: 0 (mirror.py:278)
2024-12-21 20:35:57,561 INFO: Syncing all packages. (mirror.py:293)
2024-12-21 20:36:07,589 ERROR: Call to list_packages_with_serial @ https://pypi.org/pypi timed out: Timeout on reading data from socket (master.py:198)
Traceback (most recent call last):
  File "/root/repo-mirrors/bandersnatch/.venv/bin/bandersnatch", line 8, in <module>
    sys.exit(main())
  File "/root/repo-mirrors/bandersnatch/.venv/lib64/python3.9/site-packages/bandersnatch/main.py", line 226, in main
    return asyncio.run(async_main(args, config))
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/root/repo-mirrors/bandersnatch/.venv/lib64/python3.9/site-packages/bandersnatch/main.py", line 191, in async_main
    return await bandersnatch.mirror.mirror(config)
  File "/root/repo-mirrors/bandersnatch/.venv/lib64/python3.9/site-packages/bandersnatch/mirror.py", line 986, in mirror
    changed_packages = await mirror.synchronize(
  File "/root/repo-mirrors/bandersnatch/.venv/lib64/python3.9/site-packages/bandersnatch/mirror.py", line 65, in synchronize
    await self.determine_packages_to_sync()
  File "/root/repo-mirrors/bandersnatch/.venv/lib64/python3.9/site-packages/bandersnatch/mirror.py", line 297, in determine_packages_to_sync
    all_packages = await self.master.all_packages()
  File "/root/repo-mirrors/bandersnatch/.venv/lib64/python3.9/site-packages/bandersnatch/master.py", line 203, in all_packages
    raise XmlRpcError("Unable to get full list of packages")
bandersnatch.master.XmlRpcError: Unable to get full list of packages
```
