### ISSUE TITLE
Since the Bump s3path from 0.4.2 to 0.5.0

### ISSUE THREAD

**Issue by Vorgans** [pypa/bandersnatch#1528]
Hello,

Since the new merge s3path cannot import the S3DirEntry :

```
2023-08-22 08:11:41,377 INFO: Selected storage backend: s3 (configuration.py:131)
2023-08-22 08:11:41,377 INFO: Selected compare method: hash (configuration.py:179)
Traceback (most recent call last):
  File "./bandersnatch/bin/bandersnatch", line 8, in <module>
    sys.exit(main())
  File "/builds/cloud/pypi-mirror/bandersnatch/lib/python3.8/site-packages/bandersnatch/main.py", line 226, in main
    return asyncio.run(async_main(args, config))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/builds/cloud/pypi-mirror/bandersnatch/lib/python3.8/site-packages/bandersnatch/main.py", line 191, in async_main
    return await bandersnatch.mirror.mirror(config)
  File "/builds/cloud/pypi-mirror/bandersnatch/lib/python3.8/site-packages/bandersnatch/mirror.py", line 924, in mirror
    storage_backend_plugins(
  File "/builds/cloud/pypi-mirror/bandersnatch/lib/python3.8/site-packages/bandersnatch/storage.py", line 419, in storage_backend_plugins
    return load_storage_plugins(
  File "/builds/cloud/pypi-mirror/bandersnatch/lib/python3.8/site-packages/bandersnatch/storage.py", line 386, in load_storage_plugins
    plugin_class = entry_point.load()
  File "/builds/cloud/pypi-mirror/bandersnatch/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/builds/cloud/pypi-mirror/bandersnatch/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/builds/cloud/pypi-mirror/bandersnatch/lib/python3.8/site-packages/bandersnatch_storage_plugins/s3.py", line 17, in <module>
    from s3path import PureS3Path, S3DirEntry
ImportError: cannot import name 'S3DirEntry' from 's3path'   @@(/builds/cloud/pypi-mirror/bandersnatch/lib/python3.8/site-packages/s3path.py)
```

**Comment by cooperlees** [comment]
We have not claimed support with 0.5.0 yet. We work very hard to start current and work with latest dependencies. s3path 0.5.0 was release only a few days ago.

There is a PR open that "fixes" it, but I'm asking s3path if that's our right path forward: https://github.com/pypa/bandersnatch/pull/1525 - s3path have made the type "private".

Please look at our requirements files, in this case  [requirements_s3.txt](https://github.com/pypa/bandersnatch/blob/main/requirements_s3.txt) to see what CI tests say we work with.

For now, your only option is to downgrade or apply the attempted fix.

**Comment by Vorgans** [comment]
Hi, thanks for your answer. In my case, i have try to fix it with  :

````
$ pip install -r requirements_s3.txt
Collecting boto3==1.28.26
  Downloading boto3-1.28.26-py3-none-any.whl (135 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.8/135.8 kB 5.2 MB/s eta 0:00:00
Collecting botocore==1.31.26
  Downloading botocore-1.31.26-py3-none-any.whl (11.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 66.7 MB/s eta 0:00:00
Collecting jmespath==1.0.1
  Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting python-dateutil==2.8.2
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 32.4 MB/s eta 0:00:00
Collecting s3path==0.4.2
  Downloading s3path-0.4.2-py3-none-any.whl (16 kB)
Collecting s3transfer==0.6.2
  Downloading s3transfer-0.6.2-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.8/79.8 kB 5.5 MB/s eta 0:00:00
Collecting six==1.16.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting smart-open==6.3.0
  Downloading smart_open-6.3.0-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.8/56.8 kB 8.0 MB/s eta 0:00:00
Collecting urllib3==1.26.15
  Downloading urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.9/140.9 kB [39](https://gitlab.xxx/cloud/pypi-mirror/-/jobs/74818#L39).4 MB/s eta 0:00:00
Collecting packaging
  Downloading packaging-23.1-py3-none-any.whl ([48](https://gitlab.xxx/cloud/pypi-mirror/-/jobs/74818#L48) kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 14.6 MB/s eta 0:00:00
Installing collected packages: urllib3, smart-open, six, packaging, jmespath, python-dateutil, botocore, s3transfer, boto3, s3path
Successfully installed boto3-1.28.26 botocore-1.31.26 jmespath-1.0.1 packaging-23.1 python-dateutil-2.8.2 s3path-0.4.2 s3transfer-0.6.2 six-1.16.0 smart-open-6.3.0 urllib3-1.26.15
````

But in the following installation :

````
$ python3 -m venv bandersnatch
$ bandersnatch/bin/pip install bandersnatch[s3]
Collecting bandersnatch[s3]
  Downloading bandersnatch-6.3.0-py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.6/106.6 kB 4.6 MB/s eta 0:00:00
Collecting aiohttp-xmlrpc
  Downloading aiohttp_xmlrpc-1.5.0-py3-none-any.whl (11 kB)
Collecting aiohttp-socks
  Downloading aiohttp_socks-0.8.0-py3-none-any.whl (9.4 kB)
Collecting aiohttp
  Downloading aiohttp-3.8.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 84.3 MB/s eta 0:00:00
Collecting humanfriendly
  Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 18.8 MB/s eta 0:00:00
Collecting packaging
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 13.5 MB/s eta 0:00:00
Requirement already satisfied: setuptools in ./bandersnatch/lib/python3.10/site-packages (from bandersnatch[s3]) (65.5.0)
Collecting filelock
  Downloading filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting s3path>=0.4.0
  Downloading s3path-0.5.0-py3-none-any.whl (17 kB)
Collecting smart-open
  Downloading smart_open-6.3.0-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.8/56.8 kB 17.3 MB/s eta 0:00:00
Collecting boto3>=1.16.35
  Downloading boto3-1.28.31-py3-none-any.whl (135 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.8/135.8 kB 27.9 MB/s eta 0:00:00
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2[68](https://gitlab.xxx/cloud/pypi-mirror/-/jobs/74733#L68) kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 47.8 MB/s eta 0:00:00
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 35.4 MB/s eta 0:00:00
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.4.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (225 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.7/225.7 kB 44.2 MB/s eta 0:00:00
Collecting attrs>=17.3.0
  Downloading attrs-23.1.0-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 15.0 MB/s eta 0:00:00
Collecting charset-normalizer<4.0,>=2.0
  Downloading charset_normalizer-3.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (201 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.8/201.8 kB 48.8 MB/s eta 0:00:00
Collecting python-socks[asyncio]<3.0.0,>=2.0.0
  Downloading python_socks-2.3.0-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.3/53.3 kB 17.2 MB/s eta 0:00:00
Collecting lxml
  Downloading lxml-4.9.3-cp310-cp310-manylinux_2_28_x86_64.whl (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 111.4 MB/s eta 0:00:00
Collecting jmespath<2.0.0,>=0.7.1
  Using cached jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting botocore<1.32.0,>=1.31.31
  Using cached botocore-1.31.31-py3-none-any.whl (11.1 MB)
Collecting s3transfer<0.7.0,>=0.6.0
  Using cached s3transfer-0.6.2-py3-none-any.whl ([79](https://gitlab.xxx/cloud/pypi-mirror/-/jobs/74733#L79) kB)
Collecting idna>=2.0
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 20.2 MB/s eta 0:00:00
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting urllib3<1.27,>=1.25.4
  Using cached urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: python-socks, urllib3, smart-open, six, packaging, multidict, lxml, jmespath, idna, humanfriendly, frozenlist, filelock, charset-normalizer, attrs, async-timeout, yarl, python-dateutil, aiosignal, botocore, aiohttp, s3transfer, aiohttp-xmlrpc, aiohttp-socks, boto3, bandersnatch, s3path
Successfully installed aiohttp-3.8.5 aiohttp-socks-0.8.0 aiohttp-xmlrpc-1.5.0 aiosignal-1.3.1 async-timeout-4.0.3 attrs-23.1.0 bandersnatch-6.3.0 boto3-1.28.31 botocore-1.31.31 charset-normalizer-3.2.0 filelock-3.12.2 frozenlist-1.4.0 humanfriendly-10.0 idna-3.4 jmespath-1.0.1 lxml-4.9.3 multidict-6.0.4 packaging-23.1 python-dateutil-2.8.2 python-socks-2.3.0 s3path-0.5.0 s3transfer-0.6.2 six-1.16.0 smart-open-6.3.0 urllib3-1.26.16 yarl-1.9.2
````

Can i fix the version of the s3 path with another solution ?

**Comment by Vorgans** [comment]
Hi and thanks for your answer.

I have fix it with this solution 👍 

````
python3 -m venv bandersnatch
bandersnatch/bin/pip install -r requirements_s3.txt
bandersnatch/bin/pip install --no-dependencies bandersnatch[s3]
````

In my file "requirements_s3.txt" : 
````
aiohttp==3.8.5
aiohttp-socks==0.8.0
aiohttp-xmlrpc==1.5.0
async-timeout>=4.0.0a3
attrs==23.1.0
chardet==5.2.0
filelock==3.12.2
humanfriendly==10.0
idna==3.4
lxml==4.9.3
multidict==6.0.4
packaging==23.1
pyparsing==3.1.1
setuptools==68.1.2
six==1.16.0
yarl==1.9.2
boto3==1.28.26
botocore==1.31.26
jmespath==1.0.1
python-dateutil==2.8.2
s3path==0.4.2
s3transfer==0.6.2
six==1.16.0
smart-open==6.3.0
urllib3==1.26.15
aiosignal==1.3.1
charset-normalizer==3.2.0 
frozenlist==1.4.0
python-socks==2.3.0
````
