### ISSUE TITLE
Sync from network mirror appear errors

### ISSUE THREAD

**Issue by Tu-114-s-undercarriage** [pypa/bandersnatch#167]
About the config file,  I only changed line 11:
```
master = https://pypi.tuna.tsinghua.edu.cn/simple
```
And when I execute command 

> sudo /home/username/anaconda/bin/bandersnatch mirror

There are some execptions displaied like this:
```
2019-03-05 19:10:23,252 INFO: bandersnatch/3.2.0 (cpython 3.6.3-final0, Linux x86_64)
2019-03-05 19:10:23,254 INFO: Syncing with https://pypi.tuna.tsinghua.edu.cn/simple.
2019-03-05 19:10:23,254 INFO: Current mirror serial: 4898806
2019-03-05 19:10:23,254 INFO: Syncing based on changelog.
Traceback (most recent call last):
  File "/home/username/anaconda3/bin/bandersnatch", line 10, in <module> sys.exit(main())
  File "/home/username/anaconda3/lib/python3.6/site-packages/bandersnatch/main.py", line 191, in main mirror(config)
  File "/home/username/anaconda3/lib/python3.6/site-packages/bandersnatch/main.py", line 69, in mirror changed_packages = mirror.synchronize()
  File "/home/username/anaconda3/lib/python3.6/site-packages/bandersnatch/mirror.py", line 109, in synchronize self.determine_packages_to_sync()
  File "/home/username/anaconda3/lib/python3.6/site-packages/bandersnatch/mirror.py", line 192, in determine_packages_to_sync self.master.changed_packages(self.synced_serial)
  File "/home/username/anaconda3/lib/python3.6/site-packages/bandersnatch/master.py", line 98, in changed_packages changelog = self.rpc().changelog_since_serial(last_serial)
  File "/home/username/anaconda3/lib/python3.6/site-packages/xmlrpc2/client.py", line 87, in __call__ values = self._serializer.deserialize(resp)
  File "/home/username/anaconda3/lib/python3.6/site-packages/xmlrpc2/serializer.py", line 74, in deserialize raise ValueError("xmlrpc packet not able to be deserialized")
ValueError: xmlrpc packet not able to be deserialized
```
But after I chnged master to "https://pypi.org" , it works. But in Chain the speed of download is too slow by using mirror "https://pypi.org" do you have any advice?
Thank you all.

**Comment by cooperlees** [comment]
This will not work. Bandersnatch requires the XMLRPC API to work. Static mirrors created from bandersnatch can not be used to be remirrored.

Today, PyPI is fully CDN powered across the world. What’s your advantage of hitting this mirror? (Just curious).

If it’s for bandwidth saving, maybe ask the mirror to offer rsyncd access.

**Comment by Tu-114-s-undercarriage** [comment]
Thank you for your reply, maybe I need find some other way instead of deploy a local mirror.
Have a nice day!

**Comment by hhaoao** [comment]
@Tu-114-s-undercarriage Hello, I've got this problem, too. Have you found the right way to create local pipy mirror?

**Comment by Tu-114-s-undercarriage** [comment]
> @Tu-114-s-undercarriage Hello, I've got this problem, too. Have you found the right way to create local pipy mirror?

Nope, I just allow servers access to a pypi mirror on firewall.
