### ISSUE TITLE
3.2.0 bandersantch raising FileExistsError trying to mkdir after downloading package

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#192]
Need to work out if we need to handle if a directory already exists or see if there is another bug here

Version seen on: 3.2.0

```
[2019-04-12 07:47:11,631] ERROR: Error syncing package: pyramid_oereb@5017039 (package.py:143)
Traceback (most recent call last):
  File "bandersnatch/package.py", line 120, in sync
  File "bandersnatch/package.py", line 198, in sync_release_files
  File "bandersnatch/package.py", line 184, in sync_release_files
  File "bandersnatch/package.py", line 348, in download_file
  File "/usr/local/fbcode/gcc-5-glibc-2.23/lib/python3.6/pathlib.py", line 1226, in mkdir
    self._accessor.mkdir(self, mode)
  File "/usr/local/fbcode/gcc-5-glibc-2.23/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileExistsError: [Errno 17] File exists: '/data/pypi/web/packages/5a/fa/81dc4f5cbe5dc02e89b0930bbce0f99effbbeda5dd6dfda4b2fa24520989'
```

**Comment by rene-d** [comment]
Perhaps the sync process has been interrupted between the directory creation and file download, and when it was run again, the directory already exists?

**Comment by cooperlees** [comment]
Good chance, but i think this was a bug with GlusterFS. Going to close for now.
