### ISSUE TITLE
Timeouts are not handling the timeout exception cleanly

### ISSUE THREAD

**Issue by dwighthubbard** [pypa/bandersnatch#26]
In using the current git release timeouts are causing unhandled exceptions instead of logging
timeout errors:

``` console
2018-05-23 16:47:21,785 ERROR: Error syncing package: tf-nightly-gpu@3887722
Traceback (most recent call last):
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=10.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/bandersnatch/package.py", line 117, in sync
    self.sync_release_files()
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/bandersnatch/package.py", line 183, in sync_release_files
    release_file['digests']['sha256']
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/bandersnatch/package.py", line 307, in download_file
    r = self.mirror.master.get(url, required_serial=None, stream=True)
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/bandersnatch/master.py", line 44, in get
    r = self.session.get(path, timeout=self.timeout, **kw)
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/var/virtualenv/public_mirror/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=10.0)
```

**Comment by cooperlees** [comment]
Are you still seeing this with asyncio threadpools @dwighthubbard? I would expect so - as there has been nothing to catch the timeout.

**Comment by cooperlees** [comment]
No more confirmations of this happening. Closing. Please reopen if 3.4.1 exhibits this behaviour.
