### ISSUE TITLE
Timeouts likely with verify

### ISSUE THREAD

**Issue by electricworry** [pypa/bandersnatch#286]
I think this has been reported in different forms over time (and IIRC I was involved in reporting this). However, I've revisited with the latest codebase and I'm still seeing cases where a timeout will cause the verify task to fail. The exceptions I've regularly encountered are:

```
Traceback (most recent call last):
  File "/opt/mirror/access/bandersnatch-venv/bin/bandersnatch", line 11, in <module>
    load_entry_point('bandersnatch', 'console_scripts', 'bandersnatch')()
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/main.py", line 172, in main
    loop.run_until_complete(bandersnatch.verify.metadata_verify(config, args))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/verify.py", line 220, in metadata_verify
    config, all_package_files, mirror_base, json_files, args, executor
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/verify.py", line 194, in async_verify
    await asyncio.gather(*consumers)
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/verify.py", line 186, in consume
    config, json_file, mirror_base, all_package_files, args, executor
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/verify.py", line 104, in verify
    await _get_latest_json(json_full_path, config, executor, args.delete)
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/verify.py", line 41, in _get_latest_json
    await url_fetch(url, new_json_path, executor)
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/verify.py", line 163, in url_fetch
    async with session.get(url, timeout=timeout) as response:
  File "/opt/mirror/access/bandersnatch-venv/lib/python3.6/site-packages/aiohttp/client.py", line 784, in __aenter__
    self._resp = await self._coro
  File "/opt/mirror/access/bandersnatch-venv/lib/python3.6/site-packages/aiohttp/client.py", line 409, in _request
    break
  File "/opt/mirror/access/bandersnatch-venv/lib/python3.6/site-packages/aiohttp/helpers.py", line 671, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```

```
Traceback (most recent call last):
  File "/opt/mirror/access/bandersnatch-venv/bin/bandersnatch", line 11, in <module>
    load_entry_point('bandersnatch', 'console_scripts', 'bandersnatch')()
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/main.py", line 172, in main
    loop.run_until_complete(bandersnatch.verify.metadata_verify(config, args))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/verify.py", line 226, in metadata_verify
    config, all_package_files, mirror_base, json_files, args, executor
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/verify.py", line 200, in async_verify
    await asyncio.gather(*consumers)
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/verify.py", line 192, in consume
    config, json_file, mirror_base, all_package_files, args, executor
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/verify.py", line 132, in verify
    await url_fetch(jpkg["url"], pkg_file, executor)
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/verify.py", line 166, in url_fetch
    async with session.get(url, timeout=timeout) as response:
  File "/opt/mirror/access/bandersnatch-venv/lib/python3.6/site-packages/aiohttp/client.py", line 784, in __aenter__
    self._resp = await self._coro
  File "/opt/mirror/access/bandersnatch-venv/lib/python3.6/site-packages/aiohttp/client.py", line 333, in _request
    await resp.start(conn, read_until_eof)
  File "/opt/mirror/access/bandersnatch-venv/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 753, in start
    (message, payload) = await self._protocol.read()
  File "/opt/mirror/access/bandersnatch-venv/lib/python3.6/site-packages/aiohttp/streams.py", line 533, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
```

(I believe I'm seeing these issues frequently enough that the job "verify --delete --update-json" will rarely complete and will fail early due to an exception.)

I've implemented a fix that involves a loop with X attempts in url_fetch, and that catches asyncio.TimeoutError and aiohttp.client_exceptions.ClientOSError exceptions. Do you think that would be a reasonable enough solution or is there something else you would rather implement?

**Comment by cooperlees** [comment]
Hi, Yes, this is totally worth doing. It will be totally helpful for less reliable Internet connections. Thanks for flagging.

Can we make the loop iterations and timeout values CLI configurable please. Other than that, I'll comment more in the PR!

**Comment by electricworry** [comment]
Yes that's fair. Are you able to assign the task to me, and I'll try to get it done soon?

**Comment by electricworry** [comment]
Apologies for the delay. I've not forgotten about my issues; testing a sync of multiple terabytes on a weekly basis takes a bit of time. :) Progress update: The exception handling works well. I've had a verify complete for (I think) the first time. I'll get a PR soon.

**Comment by cooperlees** [comment]
Awesome. Thanks! I'm happy to start up a Virtual Private Server with a fast connection if you'd like to test there now to finish it up faster. Email or IRC me if you'd like to.

**Comment by cooperlees** [comment]
With my refactor, verify shares the timeout settings from master.py now, so is configurable. So this should be fixed. Let me know if it's not.

**Comment by electricworry** [comment]
I'd like to reopen this if I may. I have definitely seen ServerTimeoutErrors when doing a verify, and due to the verify module having less robust error handling, the script will terminate.

Without doing a redesign (which I don't think it needs) I would like to submit a PR with some improvements to handle and log errors gracefully. I've written the changes already, but just need to add tests (which I'll also do for #762).

**Comment by cooperlees** [comment]
Awesome. Thanks @electricworry !
