### ISSUE TITLE
Enforce Dir + File permissions everywhere + Retry

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#41]
Due to GlusterFS fun I sometimes hit PermissionError with different bandersnatch IO operations. Lets ensure we're doing all we can to get correct permissions and possibly add retry logic on `PermissionError`.

```
[2018-06-16 18:45:07,467] ERROR: Error syncing package: cip-log@3937070 (package.py:146)
Traceback (most recent call last):
  File "bandersnatch/package.py", line 117, in sync
  File "bandersnatch/master.py", line 45, in get
  File "requests/models.py", line 935, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/pypi/cip-log/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bandersnatch/package.py", line 121, in sync
  File "bandersnatch/package.py", line 327, in delete
  File "/usr/local/fbcode/gcc-5-glibc-2.23/lib/python3.6/shutil.py", line 476, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/local/fbcode/gcc-5-glibc-2.23/lib/python3.6/shutil.py", line 474, in rmtree
    fd = os.open(path, os.O_RDONLY)
PermissionError: [Errno 13] Permission denied: '/data/pypi/web/pypi/cip-log'
```

When I check the directory:
```
ls -lha /data/pypi/web/pypi/cip-log
d---------      2 nobody nobody  24 Jun 12 00:14 .
```

Lets see if we can make bandersnatch try and set correct permissions and retry 'x' time(s). I'd suggest once.

**Comment by fried** [comment]
```
Traceback (most recent call last):
  File "bandersnatch/package.py", line 118, in sync
  File "bandersnatch/package.py", line 258, in sync_simple_page
  File "/usr/local/fbcode/gcc-5-glibc-2.23/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "bandersnatch/utils.py", line 68, in rewrite
  File "/usr/local/fbcode/gcc-5-glibc-2.23/lib/python3.6/tempfile.py", line 549, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/fbcode/gcc-5-glibc-2.23/lib/python3.6/tempfile.py", line 260, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/data/pypi/web/simple/c/c/.index.html.31v8csbx'
```
The issue was the web/simple/c/c directory was 000, setting it to 755 fixed the issue and the sync continued.  This is most likely some gluster interaction issue and maybe not an issue with bandersnatch per se. 

If this exception raised all the way to the top, I could remediate it in my code that calls synchronize, And just call synchronize again.

**Comment by d2gex** [comment]
Just popped in at PyPa weekend in London. I'll have a look at this if no-on is on it right now

**Comment by cooperlees** [comment]
I think this was all GlusterFS fun and games. Closing unless someone sees it again.
