### ISSUE TITLE
Verify failures

### ISSUE THREAD

**Issue by electricworry** [pypa/bandersnatch#47]
I decided to check out the latest development of bandersnatch to see how the verification is coming along. (I had pointed out [previously](https://bitbucket.org/pypa/bandersnatch/issues/94/package-files-are-never-purged) that with the new package paths it was not straightforward to identify purged files for removal.)

I can see that you're well on the way to a solution using the json metadata (good idea!). However, I'm finding the running of "bandersnatch verify" a bit fragile. It seems that a single exception causes the asyncio event loop to die:

```
2018-06-21 08:49:59,249 INFO: Finished validating jvc-proxy
2018-06-21 08:49:59,258 INFO: Finished validating djangocms-background-media
Task was destroyed but it is pending!
task: <Task pending coro=<TCPConnector._resolve_host() running at /opt/mirror/access/bandersnatch-venv/lib/python3.6/site-packages/aiohttp/connector.py:733> wait_for=<Future finished result=[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('151.101.61.63', 443)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('2a04:4e42:f::319', 443, 0, 0))]> cb=[shield.<locals>._done_callback() at /usr/lib/python3.6/asyncio/tasks.py:679]>
Traceback (most recent call last):
  File "/opt/mirror/access/bandersnatch-venv/bin/bandersnatch", line 11, in <module>
    load_entry_point('bandersnatch', 'console_scripts', 'bandersnatch')()
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/main.py", line 152, in main
    loop.run_until_complete(bandersnatch.verify.metadata_verify(config, args))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/verify.py", line 174, in metadata_verify
    config, all_package_files, mirror_base, json_files, args, executor
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/verify.py", line 148, in async_verify
    await asyncio.gather(*coros)
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/verify.py", line 95, in verify
    await url_fetch(jpkg["url"], pkg_file, executor)
  File "/opt/mirror/access/bandersnatch/src/bandersnatch/verify.py", line 128, in url_fetch
    async with session.get(url, timeout=timeout) as response:
  File "/opt/mirror/access/bandersnatch-venv/lib/python3.6/site-packages/aiohttp/client.py", line 784, in __aenter__
    self._resp = await self._coro
  File "/opt/mirror/access/bandersnatch-venv/lib/python3.6/site-packages/aiohttp/client.py", line 409, in _request
    break
  File "/opt/mirror/access/bandersnatch-venv/lib/python3.6/site-packages/aiohttp/helpers.py", line 671, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
exception calling callback for <Future at 0x7fbb5e3af0b8 state=finished returned str>
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.6/asyncio/futures.py", line 414, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 621, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 358, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
exception calling callback for <Future at 0x7fbb5e265ba8 state=finished returned str>
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.6/asyncio/futures.py", line 414, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 621, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 358, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

I'm completely new to asyncio, so I'm not sure what is the best approach. Can asyncio be configured to ignore errors and continue to the next task? Or is diligent handling of failures required as normal?

Thanks. I'd be happy to help out on this one if I can.

**Comment by cooperlees** [comment]
Thanks for reporting.

So there we're hitting `concurrent.futures._base.TimeoutError` and exception can be handled the same in async code. We should:

1) Catch these errors and report failed verifies / fetches with LOG.exception
2) With https://github.com/pypa/bandersnatch/pull/48 I expect this to be a lot better.

I believe you would of just had to many coros running for your connection / server etc.

Once that PR lands lets retry and look at handling timeouts better + further scale if you still hit issues.

**Comment by electricworry** [comment]
Thanks for your support here. I'll just do some catches to handle the exceptions for now and revisit properly on release. When is the release expected (if that's known)?

**Comment by cooperlees** [comment]
No idea, next week or so. I'll try get verify running in my Datacenters today reliably with the PR pulled and then take it from there.

**Comment by cooperlees** [comment]
This should of been fixed with the executors fix.
