### ISSUE TITLE
Fix Integration run for Windows

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#472]
Windows is failing to run bandersnatch.exe with GitHub actions.

It's currently disabled.

```
Successfully installed bandersnatch-4.0.0.dev2
Running Ingtegration tests due to TOXENV set to INTEGRATION
Setting CI directory=C:\Users\RUNNER~1\AppData\Local\Temp\pypi
Starting CI bandersnatch mirror ...
bandersnatch cmd: C:\pip\bin\bandersnatch.exe --config C:\Users\RUNNER~1\AppData\Local\Temp\pypi\ci.conf --debug mirror
Traceback (most recent call last):
  File "test_runner.py", line 149, in <module>
    exit(main())
  File "test_runner.py", line 145, in main
    return do_ci(platform_config())
  File "test_runner.py", line 93, in do_ci
    run(cmds, check=True)
  File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
##[error]Process completed with exit code 1.
```

**Comment by cooperlees** [comment]
I found bug and got it working with https://github.com/pypa/bandersnatch/pull/471
