### ISSUE TITLE
Consistently sync failure from pypi.org as we didn't handle aiohttp timeouts correctly

### ISSUE THREAD

**Issue by zxkane** [pypa/bandersnatch#477]
I'm using bandersnatch to sync from pypi.org every 5 mins. I noticed the mirror work always failed on syncing `corona-cli` since yesterday. 

Is it an issue caused by configuration and any workaround is suggested?

```
2020-03-31 11:23:35,098 ERROR: Error syncing package: corona-cli@6911612
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bandersnatch/package.py", line 145, in sync
    metadata_response = await metadata_generator.asend(None)
  File "/usr/local/lib/python3.7/site-packages/bandersnatch/master.py", line 105, in get
    await self.check_for_stale_cache(path, required_serial, got_serial)
  File "/usr/local/lib/python3.7/site-packages/bandersnatch/master.py", line 74, in check_for_stale_cache
    async with self.session.request("PURGE", path):
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/client.py", line 404, in _request
    tm = TimeoutHandle(self._loop, real_timeout.total)
AttributeError: 'float' object has no attribute 'total'
```

**Comment by cooperlees** [comment]
I missed passing correct timeout objects to aiohttp.

If you could please try and use the branch via a pip install to test for me that would be great (testing timeout with a Stale CDN is hard):
pip install git+https://github.com/pypa/bandersnatch.git@aiohttp_timeouts

Once you confirm I'll either fix more or push to PyPI. Also would like to give it another 24 hours as I expect a few more bugs with the 4.0.0 big change.

**Comment by zxkane** [comment]
The runtime exception is gone after installing from the specific branch with fix.

Still see below `ERROR` output related to stale serial. Any suggestion how fix it?

```
2020-03-31 15:00:29,022 INFO: Resuming interrupted sync from local todo list.
2020-03-31 15:00:29,028 INFO: No project filters are enabled. Skipping filtering
2020-03-31 15:00:29,029 INFO: Trying to reach serial: 6911746
2020-03-31 15:00:29,029 INFO: 1 packages to sync.
2020-03-31 15:00:29,029 INFO: Syncing package: corona-cli (serial 6911612)
2020-03-31 15:00:30,195 ERROR: Stale serial for package corona-cli - Attempt 1
2020-03-31 15:00:31,196 INFO: Syncing package: corona-cli (serial 6911612)
2020-03-31 15:00:32,449 ERROR: Stale serial for package corona-cli - Attempt 2
2020-03-31 15:00:34,451 INFO: Syncing package: corona-cli (serial 6911612)
2020-03-31 15:00:35,690 ERROR: Stale serial for package corona-cli - Attempt 3
2020-03-31 15:00:35,690 ERROR: Stale serial for corona-cli (6911612) not updating. Giving up.
2020-03-31 15:00:35,691 INFO: Generating global index page.
```

**Comment by cooperlees** [comment]
Now, since you're getting no exception, we're trying to PURGE the CDN to help, but it seems it's not helping anymore.
- You'll need to wait and see if the CDN endpoint your hitting is auto PURGED or repaired in the next 24 hours

We had reports of this on and off for a year or so and this is a dup of #56 + reported to Warehouse @ https://github.com/pypa/warehouse/issues/4892
- I've never been able to sit / IRC with a Warehouse admin and debug this one out.

**Comment by zxkane** [comment]
@cooperlees thanks for diving deep into this error msg. The same error has occurred more than 24 hours in my env, which is blocking syncing latest packages from upstream.

I reverted to using 3.6.0 now. Looks like something helps in this scenario.  The mirror task can continue now.

**Comment by cooperlees** [comment]
Ok, handy to know, thanks. I must need to do more to actually send the PURGE request with aiohttp.

I’ll manually try run it and tcpdump to make sure packets flow (I can’t see the request as it will be TLS’d) in the next few days unless someone else beats me. This is the only difference that could help you here.

**Comment by cooperlees** [comment]
So I played with the PURE code to test if we send the request. We *should* be still sending it. Using `tcpdump` and reading the logs on my personal HTTPS server (us.cooperlees.com) I saw the request be made:

Test code: https://pastebin.com/LePYDdKN
Log Line:
```
[2020-04-03 04:42:12,124] INFO: ::ffff:69.69.69.69 [03/Apr/2020:04:42:12 +0000] "PURGE /pure_test HTTP/1.1" 200 469 "-" "Python/3.7 aiohttp/3.6.2" (web_log.py:233)
```

I even tested hitting a PyPI CDN URL and got the expected JSON response ... So I don't know what else to fix here. I think I'll release 4.0.1 today where we at least pass usable timeouts to aiohttp...
- The fact you were timing out is the issue ... No idea why, I can't replicate.

**Comment by cooperlees** [comment]
@zxkane - Have you been able to move back to 4.0.1? I'm planning to release 4.0.2 later today where we have added aiohttp `raise_on_status` so that we throw client errors anywhere we get >= HTTP ERROR 400.

What do you think is our best next step here? I was unable to repro and I proved the code is sending the PURGE request ... So don't know what else to try here.

**Comment by zxkane** [comment]
@cooperlees I'll move back to latest 4.0.1 having a try again. Is there any way to enable the verbose log of bandersnatch for further investigation if the issue happens again?

**Comment by cooperlees** [comment]
@zxkane - There is only `bandersnatch --debug mirror ...`

We now also `raise_for_status()` with aiohttp (will in *4.0.2*) that I'm about to release, so this should show any failures when trying to PURGE potentially too.

**Comment by cooperlees** [comment]
Lets work on your issues in your new issue. We've addressed these things :D
