### ISSUE TITLE
Fails to mirror packages after upgrading from 3.6 to 4.0.2

### ISSUE THREAD

**Issue by zxkane** [pypa/bandersnatch#500]
After upgrading to latest 4.0.2, the mirroring always fails on syncing packages due to below errors,

```
2020-04-27 09:49:53,464 ERROR: Error syncing package: snow@7109630
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bandersnatch/package.py", line 158, in sync
    None, self.save_json_metadata, metadata
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/bandersnatch/package.py", line 128, in save_json_metadata
    self.json_pypi_symlink.symlink_to(self.json_file)
  File "/usr/lib64/python3.7/pathlib.py", line 1347, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
  File "/usr/lib64/python3.7/pathlib.py", line 437, in symlink
    return os.symlink(a, b)
FileExistsError: [Errno 17] File exists: '/data/pypi/web/json/snow' -> '/data/pypi/web/pypi/snow/json'
```
or 
```
2020-04-27 09:50:14,590 ERROR: Continuing to next file after error downloading: https://files.pythonhosted.org/packages/2a/b7/f991b317c8d71ae8a0effd5af29678ec5eedf885f7907fbbebddd22fd538/EmuPBk-1.0.tar.gz
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bandersnatch/package.py", line 288, in sync_release_files
    release_file["url"], release_file["digests"]["sha256"]
  File "/usr/local/lib/python3.7/site-packages/bandersnatch/package.py", line 449, in download_file
    chunk = await response.content.read(chunk_size)
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/streams.py", line 368, in read
    await self._wait('read')
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/streams.py", line 296, in _wait
    await waiter
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```
I tried to download same package via `wget` in same server, it can be downloaded successfully though the download speed might be slow.

Looks like the asyncio has aggressive default timeout setting.

Pls advise how to resolve above errors when using 4.0.2.

**Comment by cooperlees** [comment]
Hi,

Thanks for trying. Did you try adjusting the timeout or workers params?

What do you have both workers and timeout set to? When you used wget - how slow was it downloading? 

I’ll try simulate a slow network like yours, but I feel asyncio is more efficient at saturating your connection so we should be able to fix this with less workers. I’d suggest two maybe and a longer timeout possibly.

Cooper

**Comment by zxkane** [comment]
I'm using below conf for bandersnatch 3.6.0, no specific tuning for v4.

```conf
[mirror]
directory = ${WORKING_DIR}
master = ${UPSTREAM}
json = true
timeout = 15
workers = 10
hash-index = false
stop-on-error = false
delete-packages = false
```

The download speed of `wget` was varied from upstream. Sometimes was more than 2MB/s, sometimes just around 10KB/s. Anyway the binary was downloaded without timeout error.

I will try to tune the timeout and workers per the doc suggestion of v4.  How about the error `FileExistsError: [Errno 17] File exists:`, any suggestion for it?

**Comment by cooperlees** [comment]
The `FileExistsError` seems strange. We do check for it and remove it if it exists:
https://github.com/pypa/bandersnatch/blob/master/src/bandersnatch/package.py#L127

Are we somehow trying to sync the same package (snow in your case) multiple times and at the same time and there was a race? I'm little at a loss as to how you got this error.

Few questions for you:
- Is this continuing to happen? Can you give me a reliable way to reproduce this?
- If you manually rm that link will the sync succeed?
- Did you get to trying with say 2 or 3 workers in your config? Has that been more reliable?

**Comment by zxkane** [comment]
The pypi packages were migrated from another storage, the symbol links might were created in previous mirroring. After removing the link the sync can work in bandersnatch 4.0.3. Looks like the previous 3.6.0 version has better edge case handling in this scenario. I'm closing this issue that probably was caused by dirty data.
