### ISSUE TITLE
Verify crashes if 404 errors encountered for json data

### ISSUE THREAD

**Issue by electricworry** [pypa/bandersnatch#762]
When doing a verify, a package deleted outright from PyPI causes a failure, due to unhandled aiohttp.client_exceptions.ClientResponseError.

```
2020-12-10 16:13:03,030 INFO: Fetching https://pypi.org/pypi/bumbo-0079/json
INFO:bandersnatch.master:Fetching https://pypi.org/pypi/bumbo-0079/json
Traceback (most recent call last):
  File "/home/ubuntu/work/venv/bin/bandersnatch", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/work/venv/lib/python3.8/site-packages/bandersnatch/main.py", line 203, in main
    return loop.run_until_complete(async_main(args, config))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/work/venv/lib/python3.8/site-packages/bandersnatch/main.py", line 115, in async_main
    return await bandersnatch.verify.metadata_verify(config, args)
  File "/home/ubuntu/work/venv/lib/python3.8/site-packages/bandersnatch/verify.py", line 210, in metadata_verify
    await verify_producer(
  File "/home/ubuntu/work/venv/lib/python3.8/site-packages/bandersnatch/verify.py", line 173, in verify_producer
    await asyncio.gather(
  File "/home/ubuntu/work/venv/lib/python3.8/site-packages/bandersnatch/verify.py", line 163, in consume
    await verify(
  File "/home/ubuntu/work/venv/lib/python3.8/site-packages/bandersnatch/verify.py", line 102, in verify
    await get_latest_json(master, json_full_path, config, executor, args.delete)
  File "/home/ubuntu/work/venv/lib/python3.8/site-packages/bandersnatch/verify.py", line 35, in get_latest_json
    await master.url_fetch(url, new_json_path, executor)
  File "/home/ubuntu/work/venv/lib/python3.8/site-packages/bandersnatch/master.py", line 167, in url_fetch
    async with self.session.get(url) as response:
  File "/home/ubuntu/work/venv/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/ubuntu/work/venv/lib/python3.8/site-packages/aiohttp/client.py", line 625, in _request
    resp.raise_for_status()
  File "/home/ubuntu/work/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://pypi.org/pypi/bumbo-0079/json/')
```

Testing a fix at the moment, and will create a PR later for opinion.

**Comment by cooperlees** [comment]
Nice find. Just catch the exception and use current metadata to go delete all the artifacts! Thanks.

**Comment by electricworry** [comment]
I don't think we need to read the current metadata and delete at that point. If delete_removed_packages is true (which it is if we're deleting the json file for the missing package) then its files will be caught and deleted by the delete_unowned_files stage. Does that sound ok?

**Comment by cooperlees** [comment]
O yeah that does. It's been a long time since I've been deep in the verify code! Good call.

**Comment by cooperlees** [comment]
P.s. If you IRC, I sit in #bandersnatch in freenode if you want faster responses and to talk about stuff.

**Comment by electricworry** [comment]
Thanks! I'll get my cloak.
