### ISSUE TITLE
Windows CI hits Event loop is closed RuntimeError

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#790]
Windows seems to get Event loop closed RuntimeErrors in the Integrations test. Would be nice to root cause and cleanup if we can.

- Seems to finish successfully tho ...

```console
'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pypi\\web\\packages\\fe\\48\\d20ab5b038ac70d834b512db343c8fd4d172b35cd541e9544ea3501e3fa6\\black-18.6b0-py36-none-any.whl']
2020-12-31 18:56:19,071 INFO: Writing diff file to mirrored-files
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000143F343C550>
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\asyncio\base_events.py", line 508, in _check_closed
Error:     raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000143F343C550>
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\asyncio\base_events.py", line 508, in _check_closed
Error:     raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000143F343C550>
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\asyncio\base_events.py", line 508, in _check_closed
Error:     raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2020-12-31 18:56:19,897 DEBUG: Initializing Master's aiohttp ClientSession
```

**Comment by cooperlees** [comment]
This has not been happening and I checked latest Windows CI runs and they don't seem to do this. So closing.
https://github.com/pypa/bandersnatch/runs/6248543954?check_suite_focus=true
