### ISSUE TITLE
Setting HTTP_PROXY + HTTPS_PROXY env vars not being used to connect to pypi.org

### ISSUE THREAD

**Issue by phipsitn** [pypa/bandersnatch#823]
Hello, I'm getting the following error no matter what I do.  I've tested using bandersnatch on windows, wsl2, and with your docker and all get the same error message.  Is there any guidance you can provide?  I am behind a corporate firewall and have set HTTP_PROXY and HTTPS_PROXY in the environment before running.  Below is the full error:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\apps\python\v3_8_5_x64\local\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\apps\python\v3_8_5_x64\local\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXXXXXXXX\.virtualenvs\bandersnatch-VXMM6fMi\Scripts\bandersnatch.exe\__main__.py", line 7, in <module>
  File "c:\users\XXXXXXXXX\.virtualenvs\bandersnatch-vxmm6fmi\lib\site-packages\bandersnatch\main.py", line 207, in main
    return loop.run_until_complete(async_main(args, config))
  File "c:\apps\python\v3_8_5_x64\local\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\XXXXXXXXX\.virtualenvs\bandersnatch-vxmm6fmi\lib\site-packages\bandersnatch\main.py", line 146, in async_main
    return await bandersnatch.mirror.mirror(config)
  File "c:\users\XXXXXXXXX\.virtualenvs\bandersnatch-vxmm6fmi\lib\site-packages\bandersnatch\mirror.py", line 894, in mirror
    changed_packages = await mirror.synchronize(specific_packages)
  File "c:\users\XXXXXXXXX\.virtualenvs\bandersnatch-vxmm6fmi\lib\site-packages\bandersnatch\mirror.py", line 67, in synchronize
    await self.determine_packages_to_sync()
  File "c:\users\XXXXXXXXX\.virtualenvs\bandersnatch-vxmm6fmi\lib\site-packages\bandersnatch\mirror.py", line 282, in determine_packages_to_sync
    all_packages = await self.master.all_packages()
  File "c:\users\XXXXXXXXX\.virtualenvs\bandersnatch-vxmm6fmi\lib\site-packages\bandersnatch\master.py", line 213, in all_packages
    all_packages_with_serial = await self.rpc("list_packages_with_serial")
  File "c:\users\XXXXXXXXX\.virtualenvs\bandersnatch-vxmm6fmi\lib\site-packages\bandersnatch\master.py", line 208, in rpc
    return await method()
  File "c:\users\XXXXXXXXX\.virtualenvs\bandersnatch-vxmm6fmi\lib\site-packages\aiohttp_xmlrpc\client.py", line 96, in __remote_call
    async with self.client.post(
  File "c:\users\XXXXXXXXX\.virtualenvs\bandersnatch-vxmm6fmi\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "c:\users\XXXXXXXXX\.virtualenvs\bandersnatch-vxmm6fmi\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "c:\users\XXXXXXXXX\.virtualenvs\bandersnatch-vxmm6fmi\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "c:\users\XXXXXXXXX\.virtualenvs\bandersnatch-vxmm6fmi\lib\site-packages\aiohttp\connector.py", line 890, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "c:\users\XXXXXXXXX\.virtualenvs\bandersnatch-vxmm6fmi\lib\site-packages\aiohttp\connector.py", line 1139, in _create_proxy_connection
    transport, proto = await self._wrap_create_connection(
  File "c:\users\XXXXXXXXX\.virtualenvs\bandersnatch-vxmm6fmi\lib\site-packages\aiohttp\connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host pypi.org:443 ssl:default [The parameter is incorrect]

**Comment by cooperlees** [comment]
Hi there,

This looks 100% proxy / firewall blocking https related.

How are you setting the proxy environment variable and ensuring it works?

**Comment by phipsitn** [comment]
set HTTP_PROXY=http://nameofcorporateproxy:80
set HTTPS_PROXY=http://nameofcorporateproxy:80
No authentication required.

**Comment by cooperlees** [comment]
So my Proxy test worked for me using our CI + adding the environment variables with main (master) build of bandersnatch on my home Ubuntu 20.04.1 using a squid proxy in docker:

```
cd bandersnatch
python3.8 -m venv /tmp/tb
/tmp/tb/bin/pip install -r requirements.txt
/tmp/tb/bin/pip install -r requirements_test.txt
/tmp/tb/bin/pip install -r requirements_swift.txt


export HTTPS_PROXY=http://10.254.254.15:3128
export HTTP_PROXY=http://10.254.254.15:3128

env | grep -i proxy
HTTPS_PROXY=http://10.254.254.15:3128
HTTP_PROXY=http://10.254.254.15:3128

export TOXENV=INTEGRATION

source /tmp/tb/bin/activate
pip install -e .
python test_runner.py 2>&1 | tee /tmp/test_proxy
```

- Test Run Output: https://pastebin.com/mBPaksKr


Verify Proxy usage via tcpdump:
```
sudo tcpdump -n -nn -i any 'host 10.254.254.15'
...
22:40:10.733678 IP 10.254.254.15.3128 > 10.254.254.1.34412
```

So the code seems right. Spot anything here you're doing wrong?

**Comment by cooperlees** [comment]
Please reopen if problem exists. Heard nothing for > a month.
