### ISSUE TITLE
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host pypi.org:443 ssl:default [Network is unreachable]

### ISSUE THREAD

**Issue by eaglebrothers** [pypa/bandersnatch#866]
Traceback (most recent call last):
  File "./bin/bandersnatch", line 10, in <module>
    sys.exit(main())
  File "/tmp/venv01/lib/python3.7/site-packages/bandersnatch/main.py", line 207, in main
    return loop.run_until_complete(async_main(args, config))
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/tmp/venv01/lib/python3.7/site-packages/bandersnatch/main.py", line 146, in async_main
    return await bandersnatch.mirror.mirror(config)
  File "/tmp/venv01/lib/python3.7/site-packages/bandersnatch/mirror.py", line 894, in mirror
    changed_packages = await mirror.synchronize(specific_packages)
  File "/tmp/venv01/lib/python3.7/site-packages/bandersnatch/mirror.py", line 67, in synchronize
    await self.determine_packages_to_sync()
  File "/tmp/venv01/lib/python3.7/site-packages/bandersnatch/mirror.py", line 282, in determine_packages_to_sync
    all_packages = await self.master.all_packages()
  File "/tmp/venv01/lib/python3.7/site-packages/bandersnatch/master.py", line 213, in all_packages
    all_packages_with_serial = await self.rpc("list_packages_with_serial")
  File "/tmp/venv01/lib/python3.7/site-packages/bandersnatch/master.py", line 208, in rpc
    return await method()
  File "/tmp/venv01/lib/python3.7/site-packages/aiohttp_xmlrpc/client.py", line 103, in __remote_call
    headers=self.headers,
  File "/tmp/venv01/lib/python3.7/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/tmp/venv01/lib/python3.7/site-packages/aiohttp/client.py", line 521, in _request
    req, traces=traces, timeout=real_timeout
  File "/tmp/venv01/lib/python3.7/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/tmp/venv01/lib/python3.7/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/tmp/venv01/lib/python3.7/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/tmp/venv01/lib/python3.7/site-packages/aiohttp/connector.py", line 1032, in _create_direct_connection
    client_error=client_error,
  File "/tmp/venv01/lib/python3.7/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host pypi.org:443 ssl:default [Network is unreachable]

---------------------------------------------------------------------------------------------------------
CentOS Linux release 7.6.1810 (Core)
Python 3.7.3

Package           Version    
----------------- -----------
aiohttp           3.7.4.post0
aiohttp-socks     0.6.0      
aiohttp-xmlrpc    1.3.0      
async-timeout     3.0.1      
attrs             20.3.0     
bandersnatch      4.4.0      
certifi           2020.12.5  
chardet           4.0.0      
filelock          3.0.12     
idna              2.10       
lxml              4.6.3      
multidict         5.1.0      
packaging         20.9       
pip               19.0.3     
pyparsing         2.4.7      
python-socks      1.2.4      
requests          2.25.1     
setuptools        40.8.0     
typing-extensions 3.7.4.3    
urllib3           1.26.4     
yarl              1.6.3

**Comment by cooperlees** [comment]
Hi,
Thanks for raising. However, this PR is very in-actionable for us.

```
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host pypi.org:443 ssl:default [Network is unreachable]
```

This is generally going to be two main things:
1) Network can't reach PyPI.org
  - Can you `ping pypi.org` (or ping6)
2) SSL Related
  - Is your OS able to validate the TLS/SSL certificates etc.
  
Can you share:
- the command and bandersnatch 
- config file you are using
- `ip addr show`
- `ip route`
- `ip -6 route`

**Comment by eaglebrothers** [comment]
in centos7 is ok by do this
yum update -y nss curl libcurl

(1/3): curl-7.29.0-59.el7_9.1.x86_64.rpm               
(2/3): libssh2-1.8.0-4.el7.x86_64.rpm            
(3/3): libcurl-7.29.0-59.el7_9.1.x86_64.rpm 
--------------------------------------------------------------------
but centos6 can not update curl
curl-7.19.7-54.el6_10.x86_64
libcurl-7.19.7-54.el6_10.x86_64
nss-3.44.0-7.el6_10.x86_64

curl https://pypi.org is ok


(vnen01) [root@mirrors vnen01]#  ./bin/bandersnatch   mirror
2021-04-02 09:51:04,890 WARNING: whitelist/blacklist filter plugins will be renamed to allowlist_*/blocklist_* in version 5.0  - Documentation @ https://bandersnatch.readthedocs.io/
2021-04-02 09:51:04,891 INFO: Selected storage backend: filesystem
2021-04-02 09:51:05,038 ERROR: Unable to load entry point swift_plugin = bandersnatch_storage_plugins.swift:SwiftStorage: No module named 'keystoneauth1'
2021-04-02 09:51:05,168 INFO: Status file /var/www/html/pypi_download/status missing. Starting over.
2021-04-02 09:51:05,168 INFO: Syncing with https://pypi.org.
2021-04-02 09:51:05,168 INFO: Current mirror serial: 0
2021-04-02 09:51:05,168 INFO: Syncing all packages.
SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fb7e2743be0>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/python3.7.3/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fb7e2743be0>
transport: <_SelectorSocketTransport closing fd=7 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/python3.7.3/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fb7e26f22b0>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/python3.7.3/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fb7e26f22b0>
transport: <_SelectorSocketTransport closing fd=7 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/python3.7.3/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fb7e26fd588>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/python3.7.3/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fb7e26fd588>
transport: <_SelectorSocketTransport closing fd=7 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/python3.7.3/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fb7e26fd710>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/python3.7.3/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fb7e26fd710>
transport: <_SelectorSocketTransport closing fd=7 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/python3.7.3/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
Traceback (most recent call last):
  File "/opt/vnen01/lib/python3.7/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/base_events.py", line 986, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/base_events.py", line 1014, in _create_connection_transport
    await waiter
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/python3.7.3/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./bin/bandersnatch", line 10, in <module>
    sys.exit(main())
  File "/opt/vnen01/lib/python3.7/site-packages/bandersnatch/main.py", line 207, in main
    return loop.run_until_complete(async_main(args, config))
  File "/usr/local/python3.7.3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/opt/vnen01/lib/python3.7/site-packages/bandersnatch/main.py", line 146, in async_main
    return await bandersnatch.mirror.mirror(config)
  File "/opt/vnen01/lib/python3.7/site-packages/bandersnatch/mirror.py", line 894, in mirror
    changed_packages = await mirror.synchronize(specific_packages)
  File "/opt/vnen01/lib/python3.7/site-packages/bandersnatch/mirror.py", line 67, in synchronize
    await self.determine_packages_to_sync()
  File "/opt/vnen01/lib/python3.7/site-packages/bandersnatch/mirror.py", line 282, in determine_packages_to_sync
    all_packages = await self.master.all_packages()
  File "/opt/vnen01/lib/python3.7/site-packages/bandersnatch/master.py", line 213, in all_packages
    all_packages_with_serial = await self.rpc("list_packages_with_serial")
  File "/opt/vnen01/lib/python3.7/site-packages/bandersnatch/master.py", line 208, in rpc
    return await method()
  File "/opt/vnen01/lib/python3.7/site-packages/aiohttp_xmlrpc/client.py", line 103, in __remote_call
    headers=self.headers,
  File "/opt/vnen01/lib/python3.7/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/opt/vnen01/lib/python3.7/site-packages/aiohttp/client.py", line 521, in _request
    req, traces=traces, timeout=real_timeout
  File "/opt/vnen01/lib/python3.7/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/opt/vnen01/lib/python3.7/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/opt/vnen01/lib/python3.7/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/opt/vnen01/lib/python3.7/site-packages/aiohttp/connector.py", line 1032, in _create_direct_connection
    client_error=client_error,
  File "/opt/vnen01/lib/python3.7/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host pypi.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')]

**Comment by cooperlees** [comment]
Your python SSL/TLS environment for aiohttp is not happy here. This is all certificate validation failing. bandersnatch just uses aiohttp here. I would refer you to their documentation: https://docs.aiohttp.org/en/stable/client_advanced.html#ssl-control-for-tcp-sockets
- If we need some customizable config to work in your environment, we might accept that PR depending how invasive it is.

Maybe some of the tips here might help: https://github.com/aio-libs/aiohttp/issues/3180

**Comment by cooperlees** [comment]
Please reopen if you want to contribute to bandersnatch's use of aiohttp to help others in the future. Thanks!
